site_name: Loggy Docs
site_url: http://101.34.53.69:18080/
copyright: Copyright &copy; 2023 - 2024 Code123

nav:
  - 首页: index.md
  - 安装: install/install.md
  - 配置: filebeat/filebeat.md
  - 截图: screenshots/screenshots.md



plugins:
#  - optimize
  - search:
      min_search_length: 2
      separator: '[\s\-\.]+'
      lang: ja
      indexing: 'full'
#  - mkdocs-simple-hooks:
#hooks:
#  - hooks.py
theme:
  name: mkdocs
  locale: zh_CN
  custom_dir: custom_theme/
extra_css:
  - style.css
use_directory_urls: false
markdown_extensions:
  - smarty